//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("IVSoftware.Portable.Xml.Linq.XBoundObject")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023-2025 IVSoftware LLC")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(@"
			A lightweight extension for System.Xml.Linq that adds runtime object binding, hierarchical modeling, and flexible path resolution via enriched XAttribute support. Includes enum-based metadata, tree construction from flat paths, and event-driven behaviors — ideal for dynamic UIs, workflows, and cross-platform .NET apps. (Ever wish XAttribute had a Tag property? Now it does.)
		")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.0.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.0.3+f615912a5bc5432f99a061b93fe33211e9355246")]
[assembly: System.Reflection.AssemblyProductAttribute("IVSoftware.Portable.Xml.Linq.XBoundObject")]
[assembly: System.Reflection.AssemblyTitleAttribute("IVSoftware.Portable.Xml.Linq.XBoundObject")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.0.3.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/IVSoftware/IVSoftware.Portable.Xml.Linq.XBoundObject.git")]

// Generated by the MSBuild WriteCodeFragment class.

